version: '3.8'

services:
  web:
    build: .
    command: python /blog_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/blog_project
    ports:
       - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
 
    environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"
  smtp:
    image: namshi/smtp
    container_name: smtp_relay
    restart: always
    ports:
     - "25:25"
    

volumes: 
  postgres_data:




    